export const PLAYER_INIT = 'PLAYER_INIT'
export const PLAYER_INIT_SUCCESSFUL = 'PLAYER_INIT_SUCCESSFUL'
export const PLAYER_INIT_FAILED = 'PLAYER_INIT_FAILED'

export const PLAYER_PLAY_NEW_EPISODE = 'PLAYER_PLAY_NEW_EPISODE'
export const PLAYER_PLAY_NEW_EPISODE_SUCCESSFUL = 'PLAYER_PLAY_NEW_EPISODE_SUCCESSFUL'
export const PLAYER_PLAY_NEW_EPISODE_FAILED = 'PLAYER_PLAY_NEW_EPISODE_FAILED'

export const PLAYER_TOGGLE_PLAY = 'PLAYER_TOGGLE_PLAY'

export const PLAYER_RUN_UPDATE_PLAYER_STATUS = 'PLAYER_RUN_UPDATE_PLAYER_STATUS'
export const PLAYER_UPDATE_PLAYER_STATUS = 'PLAYER_UPDATE_PLAYER_STATUS'
